"""Initial migration

Revision ID: 0aa2764bd867
Revises: 
Create Date: 2024-11-14 22:59:04.714066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa2764bd867'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_address', sa.String(length=255), nullable=True),
    sa.Column('intersection_type', sa.String(length=100), nullable=True),
    sa.Column('intersection_street', sa.String(length=255), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('object_detection_status', sa.String(length=50), nullable=True),
    sa.Column('ai_testing_tool_status', sa.String(length=50), nullable=True),
    sa.Column('generate_test_cases_status', sa.String(length=50), nullable=True),
    sa.Column('retrieve_test_cases_status', sa.String(length=50), nullable=True),
    sa.Column('context_tree_url', sa.String(length=255), nullable=True),
    sa.Column('input_tree_url', sa.String(length=255), nullable=True),
    sa.Column('output_tree_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subkey', sa.String(length=50), nullable=True),
    sa.Column('script_url', sa.String(length=255), nullable=True),
    sa.Column('xml_url', sa.String(length=255), nullable=True),
    sa.Column('checkpoint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_cases')
    op.drop_table('checkpoints')
    op.drop_table('trips')
    # ### end Alembic commands ###
