"""Initial migration.

Revision ID: 86155f467c5a
Revises: 0aa2764bd867
Create Date: 2024-11-15 00:37:25.516221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86155f467c5a'
down_revision = '0aa2764bd867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    op.drop_table('test_cases')
    op.drop_table('checkpoints')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoints',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('location_address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('intersection_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('intersection_street', sa.VARCHAR(length=255), nullable=True),
    sa.Column('trip_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('object_detection_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ai_testing_tool_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('generate_test_cases_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('retrieve_test_cases_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('context_tree_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('input_tree_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('output_tree_url', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subkey', sa.VARCHAR(length=50), nullable=True),
    sa.Column('script_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('xml_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('checkpoint_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('origin', sa.VARCHAR(length=255), nullable=True),
    sa.Column('destination', sa.VARCHAR(length=255), nullable=True),
    sa.Column('distance', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
